### ISSUE TITLE
isGIF

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#109]
```
Traceback (most recent call last):
 File "pixelOvalsMuchBetter.py", line 10, in <module>
 File "drawBot/drawBotDrawingTools.pyc", line 1864, in imageSize
UnboundLocalError: local variable '_isGIF' referenced before assignment
```

**Comment by typemytype** [comment]
``` python
path = u"/Users/frederik/Pictures/screenShots/Screen Shot 2017-10-24 at 11.26.53.png"
print imageSize(path)
ob = ImageObject(path)
print imageSize(ob)
```
