### ISSUE TITLE
DrawBot 3.104 does not launch

### ISSUE THREAD

**Issue by karstenw** [typemytype/drawbot#128]
On 10.10.5 DrawBot does not launch.

When started from Terminal:

% ./DrawBot.app/Contents/MacOS/DrawBot 
Traceback (most recent call last):
  File "./DrawBot.app/Contents/Resources/__boot__.py", line 54, in <module>
    _run()
  File "./DrawBot.app/Contents/Resources/__boot__.py", line 49, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "./DrawBot.app/Contents/Resources/DrawBot.py", line 1, in <module>
    import AppKit
  File "AppKit/__init__.pyc", line 8, in <module>
  File "objc/__init__.pyc", line 28, in <module>
  File "objc/_bridgesupport.pyc", line 13, in <module>
  File "pkg_resources/__init__.pyc", line 51, in <module>
ImportError: No module named moves

I did find a "moves" module as part of "future" in my user Python but not in the System Python.

**Comment by justvanrossum** [comment]
Ouch :(

**Comment by karstenw** [comment]
Fixed with 3.105

**Comment by typemytype** [comment]
thanks for testing!!
