### ISSUE TITLE
Placint a GIF from a URL fails

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#189]
Probably because it's an animated gif. Using the same gif locally works.

```python
image('https://lumiere-a.akamaihd.net/v1/images/aliceinwonderland_-yes_celebrate_bc506b50.gif', (100,100))
```

```
gifsicle: /v1/images/aliceinwonderland_-yes_celebrate_bc506b50.gif: No such file or directory
Traceback (most recent call last):
  File "/Users/just/code/git/drawbot/drawBot/ui/drawBotController.py", line 120, in createContext
    _drawBotDrawingTool._drawInContext(context)
  File "/Users/just/code/git/drawbot/drawBot/drawBotDrawingTools.py", line 121, in _drawInContext
    attr(*args, **kwargs)
  File "/Users/just/code/git/drawbot/drawBot/context/baseContext.py", line 2260, in image
    self._image(path, (x, y), alpha, pageNumber)
  File "/Users/just/code/git/drawbot/drawBot/context/pdfContext.py", line 276, in _image
    _isPDF, image = self._getImageSource(path, pageNumber)
  File "/Users/just/code/git/drawbot/drawBot/context/pdfContext.py", line 254, in _getImageSource
    pageNumber = gifTools.gifFrameCount(url)
  File "/Users/just/code/git/drawbot/drawBot/context/tools/gifTools.py", line 79, in gifFrameCount
    _explodeGif(path)
  File "/Users/just/code/git/drawbot/drawBot/context/tools/gifTools.py", line 61, in _explodeGif
    executeExternalProcess(cmds, cwd=destRoot)
  File "/Users/just/code/git/drawbot/drawBot/misc.py", line 313, in executeExternalProcess
    raise RuntimeError("%r failed with error code %s" % (os.path.basename(cmds[0]), p.returncode))
RuntimeError: 'gifsicle' failed with error code 1
```

**Comment by typemytype** [comment]
it a local download seems required for gifsicle...

**Comment by justvanrossum** [comment]
I'm fine with not supporting this case, but then there should be a better error message.

**Comment by typemytype** [comment]
it works with other image formats....

**Comment by justvanrossum** [comment]
I wonder why gifsicle needs to be involved in the first place. I don't think there's anything wrong with placing an animated gif in static content.

**Comment by typemytype** [comment]
drawBot uses gifsicle to extract single frames...

**Comment by justvanrossum** [comment]
I know that. My question is: is that necessary? An animated gif is still just a gif.

**Comment by typemytype** [comment]
similar as to pdf you could pick a frame from a gif and draw that as an image

**Comment by justvanrossum** [comment]
Right, I forgot about that, makes sense.

To fix this issue, the gif would need to be written to a temp file before being processed/placed.

**Comment by justvanrossum** [comment]
Looking at gifTools.py:
- I'm not sure why all frames are exploded: one can get at the frame count by looking at the `gifsicle -I` output, and one can extract single frames with `gifsicle input.gif '#0' > frame0.gif`
- Also, cleaning up of the exploded cache depends on `endDrawing()` being called.

I suggest to get rid of the caching, and extract frames on demand.
