### ISSUE TITLE
DrawBot py3 – missing font with savedState()

### ISSUE THREAD

**Issue by jo-lang** [typemytype/drawbot#198]
If the typeface of ```font()``` is not found Drawbot prints a nice warning in python 2.7
In the python3 version it does not print a warning if ```text()``` is called after a ```savedState()```. 
eg:
```
font('Menl')
with savedState(): text('lalalal', (100,100))
```
will print 
```
Traceback (most recent call last):
  File "<untitled>", line 6, in <module>
  File "drawBot/drawBotDrawingTools.pyc", line 71, in __enter__
  File "drawBot/drawBotDrawingTools.pyc", line 484, in save
  File "drawBot/context/baseContext.pyc", line 1875, in save
  File "drawBot/context/baseContext.pyc", line 1693, in copy
  File "drawBot/context/baseContext.pyc", line 1473, in copy
  File "drawBot/context/baseContext.pyc", line 849, in __init__
  File "drawBot/context/baseContext.pyc", line 857, in _setAttribute
  File "drawBot/context/baseContext.pyc", line 1288, in openTypeFeatures
  File "drawBot/context/baseContext.pyc", line 1301, in listOpenTypeFeatures
AttributeError: 'list' object has no attribute 'update'
```

**Comment by typemytype** [comment]
I cannot reproduce this with the lastes version. Accidentally fixed!

if not reopen :)
