### ISSUE TITLE
commit 1b787eb breaks Python2.7 compatibility

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#242]
I have DrawBot 3.117 installed as a Python module, both for Python 2.7, and for Python 3. 
The commit 1b787eb seems to break Python 2 compatibility:

``` python
import os
from drawBot import *

newDrawing()
newPage('A4')
stroke(0)
strokeWidth(10)
line((0, 0), (100, 100))
endDrawing()

saveImage(os.path.expanduser('~/Desktop/output.pdf'))
```
```
Traceback (most recent call last):
  File "grid_test.py", line 8, in <module>
    line((0, 0), (100, 100))
  File "/usr/local/lib/python2.7/site-packages/drawBot-3.117-py2.7.egg/drawBot/drawBotDrawingTools.py", line 696, in line
    path.moveTo(point1)
  File "/usr/local/lib/python2.7/site-packages/drawBot-3.117-py2.7.egg/drawBot/context/baseContext.py", line 112, in moveTo
    super().moveTo(point)
TypeError: super() takes at least 1 argument (0 given)
```

It’s fine to break compatibility with Python2 (I can convert my old scripts), but I’d like it to be explicit.
 (which is fine, but I’d like it to be explicit)

**Comment by typemytype** [comment]
oh, yeah, I reaalllly like the py3 `super()` with self and classname

but for now will fix it
