### ISSUE TITLE
bezierPath addComponent

### ISSUE THREAD

**Issue by sarahtilley** [typemytype/drawbot#246]
```Traceback (most recent call last):
  File "<untitled>", line 11, in <module>
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.6/defcon/objects/glyph.py", line 471, in draw
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.6/defcon/objects/glyph.py", line 483, in drawPoints
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.6/defcon/objects/component.py", line 188, in drawPoints
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.6/fontTools/pens/pointPen.py", line 204, in addComponent
  File "drawBot/context/baseContext.pyc", line 211, in addComponent
TypeError: addComponent() takes 3 positional arguments but 4 were given```

**Comment by justvanrossum** [comment]
Thanks for reporting! It's fixed for the next release.

**Comment by sarahtilley** [comment]
Thanks!
