### ISSUE TITLE
textBox(txt, path) chokes on empty path

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#273]
I think it would be fine for textBox() to return quickly when the text path is empty, and simply not draw anything.

```python
bez = BezierPath()
textBox("Hiii!", bez)
```

```
Traceback (most recent call last):
  File "<untitled>", line 3, in <module>
  File "/Users/just/code/git/drawbot/drawBot/drawBotDrawingTools.py", line 1779, in textBox
    return self._dummyContext.clippedText(txt, box, align)
  File "/Users/just/code/git/drawbot/drawBot/context/baseContext.py", line 2293, in clippedText
    path, origin = self._getPathForFrameSetter(box)
  File "/Users/just/code/git/drawbot/drawBot/context/baseContext.py", line 2334, in _getPathForFrameSetter
    path = box._getCGPath()
  File "/Users/just/code/git/drawbot/drawBot/context/baseContext.py", line 380, in _getCGPath
    x, y, _, _ = self.bounds()
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/just/code/git/drawbot/drawBot/ui/drawBotController.py", line 119, in createContext
    _drawBotDrawingTool._drawInContext(context)
  File "/Users/just/code/git/drawbot/drawBot/drawBotDrawingTools.py", line 121, in _drawInContext
    attr(*args, **kwargs)
  File "/Users/just/code/git/drawbot/drawBot/context/baseContext.py", line 2361, in textBox
    self._textBox(txt, box, align)
  File "/Users/just/code/git/drawbot/drawBot/context/pdfContext.py", line 148, in _textBox
    path, (x, y) = self._getPathForFrameSetter(box)
  File "/Users/just/code/git/drawbot/drawBot/context/baseContext.py", line 2334, in _getPathForFrameSetter
    path = box._getCGPath()
  File "/Users/just/code/git/drawbot/drawBot/context/baseContext.py", line 380, in _getCGPath
    x, y, _, _ = self.bounds()
TypeError: 'NoneType' object is not iterable
```

**Comment by typemytype** [comment]
I cannot reproduce this anymore...

**Comment by justvanrossum** [comment]
Me neither... Closing.
