### ISSUE TITLE
Confusing traceback when wrong data type is used for text

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#276]
(Found out in the context of a workshop)

When using an integer in a text field, the traceback is too complicated:
```
for n in range(10):
    page_number = n + 1
    newPage(100, 100)
    text(page_number, (10, 10))
```

```
/Applications/DrawBot.app/Contents/Resources/lib/python36.zip/drawBot/context/baseContext.py:1134: UninitializedDeallocWarning: leaking an uninitialized object of type NSConcreteAttributedString
Traceback (most recent call last):
  File "<untitled>", line 4, in <module>
  File "drawBot/drawBotDrawingTools.pyc", line 1597, in text
  File "drawBot/context/baseContext.pyc", line 2209, in attributedString
  File "drawBot/context/baseContext.pyc", line 1134, in append
ValueError: NSInvalidArgumentException - -[OC_BuiltinPythonNumber length]: unrecognized selector sent to instance 0x6000000b6c00
```

It would be cool (and less scary for students) to say something like “Text needs to be a string”.
Thanks!

**Comment by typemytype** [comment]
must a string.. you are providing a int

this must be checked and raising a nice clear error ;)

**Comment by typemytype** [comment]
must happen here https://github.com/typemytype/drawbot/blob/master/drawBot/drawBotDrawingTools.py

and in the bezierPath textBox

**Comment by frankrolf** [comment]
I’m aware it must be a string, but the error is a little verbose 📃😱
