### ISSUE TITLE
DrawBot crashes on start up after update 3.70

### ISSUE THREAD

**Issue by thomgb** [typemytype/drawbot#28]
:(

**Comment by justvanrossum** [comment]
```
EmBeeProRetina-6:Desktop just$ ./DrawBot.app/Contents/MacOS/DrawBot 
Traceback (most recent call last):
  File "/Users/just/Desktop/DrawBot.app/Contents/Resources/__boot__.py", line 54, in <module>
    _run()
  File "/Users/just/Desktop/DrawBot.app/Contents/Resources/__boot__.py", line 49, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/just/Desktop/DrawBot.app/Contents/Resources/DrawBot.py", line 150, in <module>
    PyObjCTools.AppHelper.runEventLoop()
AttributeError: 'module' object has no attribute 'AppHelper'
2016-01-11 20:27:32.186 DrawBot[33606:1315612] DrawBot Error
```

**Comment by justvanrossum** [comment]
(It runs fine from source.)

**Comment by typemytype** [comment]
I pushed a new download, please check again...

**Comment by thomgb** [comment]
:+1: Works fine again! Thanks for the quick fix.

**Comment by typemytype** [comment]
just to be sure I touched the version number https://github.com/typemytype/drawbot/commit/42b4da38958ffadd1125c4b9bdb9e9c208ec9fed
