### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by yeousemite** [typemytype/drawbot#362]
MacOS : Mojave 10.14.6
DrawBot Version : 3.123
Existing Python Environment: Python 3.7.7 installed through Anaconda3

Hi, I'm trying to use numpy and keep getting this error. Would you have any insight and if there is a workaround for this type of issue? :( 

Thanks!

```
Traceback (most recent call last):
  File "/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/__init__.py", line 24, in <module>
  File "/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/multiarray.py", line 14, in <module>
  File "/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/overrides.py", line 7, in <module>
ImportError: dlopen(/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
	/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/_multiarray_umath.cpython-37m-darwin.so: code signature in (/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/_multiarray_umath.cpython-37m-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<untitled>", line 1, in <module>
  File "/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/__init__.py", line 142, in <module>
  File "/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/__init__.py", line 54, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/Applications/DrawBot.app/Contents/MacOS/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dlopen(/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
	/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/_multiarray_umath.cpython-37m-darwin.so: code signature in (/Users/lynneyun/Library/Application Support/DrawBot/Python3.7/numpy/core/_multiarray_umath.cpython-37m-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

This is my path info in case it's relevant:
```
/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/lynneyun/opt/anaconda3/bin:/Users/lynneyun/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin

```

**Comment by typemytype** [comment]
this is solved here: https://github.com/typemytype/drawbot/commit/d21a133dad6191028a8b860665b68edccf790197

I just need to make a release

thanks!!

**Comment by yeousemite** [comment]
Awesome thank you so much!

**Comment by justvanrossum** [comment]
A new release is out now. Can you check whether it resolves your issue? Thanks!

**Comment by MauriceMeilleur** [comment]
`import numpy`

works just fine. Also, 

```
from pagebot.document import Document
from pagebot.elements import newRect
from pagebot.conditions import Center2Center, Middle2Middle
from pagebot.toolbox.units import pt
from pagebot.toolbox.color import color

W, H = pt(500, 400)
doc = Document(w=W, h=H, autoPages=1)
page = doc[1]

# Create a new rectangle element with position conditions
newRect(parent=page, fill=color('red'), size=pt(240, 140),
    # Show measure lines on the element.
    showDimensions=True, 
    conditions=[Center2Center(), Middle2Middle()])
# Make the page apply all conditions.
page.solve() 
# Export the document page as png, so it shows as web image.
doc.export('_export/RedSquare.png') 
```
works properly.
<img width="1792" alt="Screen Shot 2020-03-28 at 9 30 39 AM" src="https://user-images.githubusercontent.com/27898556/77825369-dc539980-70d6-11ea-8b27-9bfaa3e1ee06.png">

**Comment by typemytype** [comment]
super thanks for checking!!!

**Comment by yeousemite** [comment]
Ah great! I've been using the Python module for the past two weeks to use numpy, but great to know to the app works now too!
