### ISSUE TITLE
DrawBot 3.124 -> Install Python Packages -> install tornado

### ISSUE THREAD

**Issue by michielkauwatjoe** [typemytype/drawbot#377]
Still having issues installing through the internal package manager:

```
Collecting tornado
  Using cached tornado-6.0.4.tar.gz (496 kB)
    ERROR: Command errored out with exit status 1:
     command: /Applications/DrawBot.app/Contents/MacOS/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-jqjk6kw3/tornado/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-jqjk6kw3/tornado/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base /private/tmp/pip-install-jqjk6kw3/tornado/pip-egg-info
         cwd: /private/tmp/pip-install-jqjk6kw3/tornado/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setuptools/__init__.pyc", line 19, in <module>
      File "setuptools/dist.pyc", line 28, in <module>
      File "setuptools/extern/__init__.pyc", line 54, in load_module
    ImportError: The 'ordered_set' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by typemytype** [comment]
got the same traceback with a simple `import setuptools`

**Comment by michielkauwatjoe** [comment]
@typemytype not sure if it's the same, but installing `ordered-set` gives:

```
Collecting ordered-set
  Using cached ordered-set-3.1.1.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /Applications/DrawBot.app/Contents/MacOS/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-zx52qdrq/ordered-set/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-zx52qdrq/ordered-set/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base /private/tmp/pip-install-zx52qdrq/ordered-set/pip-egg-info
         cwd: /private/tmp/pip-install-zx52qdrq/ordered-set/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setuptools/__init__.pyc", line 232, in <module>
      File "setuptools/monkey.pyc", line 101, in patch_all
      File "setuptools/monkey.pyc", line 138, in patch_for_msvc_specialized_compiler
      File "importlib/__init__.pyc", line 127, in import_module
    ModuleNotFoundError: No module named 'setuptools.msvc'
```
which is similar to the error in the previous issue.

**Comment by justvanrossum** [comment]
Somehow setuptools is not correctly/completely bundled. We may need to add more things to our setupApp.py script.

**Comment by typemytype** [comment]
I would include `setuptools` completely 

and probably include `packaging` back in. 
its been excluded here https://github.com/typemytype/drawbot/pull/354, but I don't remember why... or what the build error was.

**Comment by typemytype** [comment]
please try https://github.com/typemytype/drawbot/releases/tag/3.125

**Comment by michielkauwatjoe** [comment]
Perfect, thank you!
