### ISSUE TITLE
text() with an empty string error

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#389]
👋

I think one of the latest releases introduces a bug. If I run this
`text('', (0, 0))`

i get this

```console
Traceback (most recent call last):
  File "<untitled>", line 1, in <module>
  File "drawBot/drawBotDrawingTools.pyc", line 1622, in text
  File "drawBot/context/baseContext.pyc", line 959, in makeTextBoxes
IndexError: tuple index out of range
```

a couple of weeks ago it was not there 🤷‍♂️

**Comment by justvanrossum** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by roberto-arista** [comment]
so quick! ⚡️

**Comment by typemytype** [comment]
will tag a release later on today
