### ISSUE TITLE
formattedText set fill to None

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#44]
Traceback (most recent call last):
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBotController.py", line 173, in createContext
    _drawBotDrawingTool._drawInContext(context)
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/drawBotDrawingTools.py", line 100, in _drawInContext
    attr(_args, *_kwargs)
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py", line 1592, in textBox
    self._textBox(txt, (x, y, w, h), align)
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/pdfContext.py", line 178, in _textBox
    self._pdfFillColor(fillColor)
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/pdfContext.py", line 276, in _pdfFillColor
    cgColor = self._nsColorToCGColor(c)
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/pdfContext.py", line 328, in _nsColorToCGColor
    if c.numberOfComponents() == 5:
AttributeError: 'NSNull' object has no attribute 'numberOfComponents'

**Comment by typemytype** [comment]
solved somewhere along the road...
