### ISSUE TITLE
DrawBot on Python 3.10?

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#443]
I recently installed Python 3.10, and just installed drawBot via pip.
When I try to run a script, this happens:

```
Python 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:20) [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import drawBot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/drawBot/__init__.py", line 1, in <module>
    from .drawBotDrawingTools import _drawBotDrawingTool
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/drawBot/drawBotDrawingTools.py", line 2561, in <module>
    _drawBotDrawingTool = DrawBotDrawingTool()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/drawBot/drawBotDrawingTools.py", line 79, in __init__
    self._reset()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/drawBot/drawBotDrawingTools.py", line 131, in _reset
    self._dummyContext = DummyContext()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/drawBot/context/baseContext.py", line 2104, in __init__
    self.reset()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/drawBot/context/baseContext.py", line 2160, in reset
    self._state = self._graphicsStateClass()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/drawBot/context/baseContext.py", line 1982, in __init__
    self.fillColor = self._colorClass(0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/drawBot/context/baseContext.py", line 824, in __init__
    self._color = self._color.colorUsingColorSpace_(self.colorSpace())
TypeError: Need 1 arguments, got 1
```

**Comment by frankrolf** [comment]
I am on macOS 11.6 (20G165), Python is 3.10.0

**Comment by frankrolf** [comment]
(I see Python embedded within the standalone application is 3.7 – I just may be too far ahead with my Python choice)

**Comment by typemytype** [comment]
uehm `TypeError: Need 1 arguments, got 1` that should be just enough... 

(I didnt test this on 3.10 yet)

**Comment by justvanrossum** [comment]
Reproducer:

```python
from AppKit import NSColorSpace

class Foo:
    colorSpace = NSColorSpace.genericRGBColorSpace


cs = NSColorSpace.genericRGBColorSpace()  # success
f = Foo()
cs = f.colorSpace()  # fail
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Need 1 arguments, got 1
```

**Comment by justvanrossum** [comment]
It seems the object is now accepted as a callable and therefore seen as a method. I'll raise a question on the pyobjc repo.

**Comment by justvanrossum** [comment]
Oh, csn sldop reproduce on 3.9. Maybe it's just the latest PyObjC. Will now test on 3.7.

**Comment by justvanrossum** [comment]
3.7 + 3.8 are ok, this happens only on 3.9 and 3.10. PyObjC 8.0 in all cases.

**Comment by typemytype** [comment]
Thanks for testing all the possibilities!

**Comment by frankrolf** [comment]
Thank you! 😊
