### ISSUE TITLE
Fresh install is broken

### ISSUE THREAD

**Issue by robertjanes** [typemytype/drawbot#465]
I tried installing on my new machine (MacOS Monterey 12.0.1) using the standard install command:
```
pip install git+https://github.com/typemytype/drawbot
```

And the install is broken as it requires PIP:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/drawBot/__init__.py", line 1, in <module>
    from .drawBotDrawingTools import _drawBotDrawingTool
  File "/opt/homebrew/lib/python3.9/site-packages/drawBot/drawBotDrawingTools.py", line 10, in <module>
    from .context import getContextForFileExt, getContextOptions, getFileExtensions, getContextOptionsDocs
  File "/opt/homebrew/lib/python3.9/site-packages/drawBot/context/__init__.py", line 8, in <module>
    from .imageObjectContext import PILContext, NSImageContext
  File "/opt/homebrew/lib/python3.9/site-packages/drawBot/context/imageObjectContext.py", line 1, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

Does `pillow` need to be added to `install_requires` of the setup.py?

**Comment by justvanrossum** [comment]
Ah yes, that seems to be an oversight in a recent change. Would you be willing to make a PR?

**Comment by robertjanes** [comment]
@justvanrossum Sure, done!
https://github.com/typemytype/drawbot/pull/466

**Comment by justvanrossum** [comment]
Thank you very much!
