### ISSUE TITLE
ImageObject.opTile() error

### ISSUE THREAD

**Issue by chrisjansky** [typemytype/drawbot#546]
Hello,

I tried using the `opTile()` filter and got the following error using this minimal setup:

```
foo = ImageObject()
foo.open("...jpg")
foo.opTile(center=(500, 500), scale=1, angle=1, width=1)
image(foo, (0, 0))
```

Error:
```
Traceback (most recent call last):
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.9/drawBot/ui/drawBotController.py", line 117, in createContext
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.9/drawBot/drawBotDrawingTools.py", line 101, in _drawInContext
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.9/drawBot/context/baseContext.py", line 2594, in image
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.9/drawBot/context/pdfContext.py", line 280, in _image
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.9/drawBot/context/pdfContext.py", line 269, in _getImageSource
objc.error: NSInternalInconsistencyException - Invalid parameter not satisfying: cgImage != NULL
```

I haven’t found any documented use of `opTile()` anywhere, is it supposed to be working?

Thanks!

**Comment by typemytype** [comment]
mmm, it looks like those filters create a infinite extent... drawBot needs to clip it to the original imageObject size

 https://developer.apple.com/documentation/coreimage/ciimage/1437833-imagebycroppingtorect?language=objc

**Comment by chrisjansky** [comment]
@typemytype Yes, that works, thank you for the quick fix!
