### ISSUE TITLE
DrawBot v3.85 as Module gives Error during import

### ISSUE THREAD

**Issue by typoman** [typemytype/drawbot#61]
Hi there :)

I installed the  current version (3.85) as a module and this was the Output in terminal:
```
drawbot$     python setupAsModule.py install
*** Warning: drawBot requires FontTools, see:
    https://github.com/behdad/fonttools
2016-10-09 18:37:55.300 Python[5108:453688] Error loading /Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView:  dlopen(/Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView, 265): no suitable image found.  Did find:
	/Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView: file too short
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/drawBot
copying drawBot/__init__.py -> build/lib/drawBot
copying drawBot/drawBotDrawingTools.py -> build/lib/drawBot
copying drawBot/misc.py -> build/lib/drawBot
copying drawBot/scriptTools.py -> build/lib/drawBot
copying drawBot/updater.py -> build/lib/drawBot
creating build/lib/drawBot/context
copying drawBot/context/__init__.py -> build/lib/drawBot/context
copying drawBot/context/baseContext.py -> build/lib/drawBot/context
copying drawBot/context/drawBotContext.py -> build/lib/drawBot/context
copying drawBot/context/dummyContext.py -> build/lib/drawBot/context
copying drawBot/context/gifContext.py -> build/lib/drawBot/context
copying drawBot/context/imageContext.py -> build/lib/drawBot/context
copying drawBot/context/movContext.py -> build/lib/drawBot/context
copying drawBot/context/pdfContext.py -> build/lib/drawBot/context
copying drawBot/context/printContext.py -> build/lib/drawBot/context
copying drawBot/context/svgContext.py -> build/lib/drawBot/context
creating build/lib/drawBot/context/tools
copying drawBot/context/tools/__init__.py -> build/lib/drawBot/context/tools
copying drawBot/context/tools/gifTools.py -> build/lib/drawBot/context/tools
copying drawBot/context/tools/imageObject.py -> build/lib/drawBot/context/tools
copying drawBot/context/tools/openType.py -> build/lib/drawBot/context/tools
creating build/lib/drawBot/ui
copying drawBot/ui/__init__.py -> build/lib/drawBot/ui
copying drawBot/ui/codeEditor.py -> build/lib/drawBot/ui
copying drawBot/ui/debug.py -> build/lib/drawBot/ui
copying drawBot/ui/drawBotController.py -> build/lib/drawBot/ui
copying drawBot/ui/drawView.py -> build/lib/drawBot/ui
copying drawBot/ui/lineNumberRulerView.py -> build/lib/drawBot/ui
copying drawBot/ui/preferencesController.py -> build/lib/drawBot/ui
copying drawBot/ui/splitView.py -> build/lib/drawBot/ui
running install_lib
creating /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot
copying build/lib/drawBot/__init__.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot
creating /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/__init__.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/baseContext.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/drawBotContext.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/dummyContext.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/gifContext.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/imageContext.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/movContext.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/pdfContext.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/printContext.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
copying build/lib/drawBot/context/svgContext.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context
creating /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/tools
copying build/lib/drawBot/context/tools/__init__.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/tools
copying build/lib/drawBot/context/tools/gifTools.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/tools
copying build/lib/drawBot/context/tools/imageObject.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/tools
copying build/lib/drawBot/context/tools/openType.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/tools
copying build/lib/drawBot/drawBotDrawingTools.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot
copying build/lib/drawBot/misc.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot
copying build/lib/drawBot/scriptTools.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot
creating /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui
copying build/lib/drawBot/ui/__init__.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui
copying build/lib/drawBot/ui/codeEditor.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui
copying build/lib/drawBot/ui/debug.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui
copying build/lib/drawBot/ui/drawBotController.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui
copying build/lib/drawBot/ui/drawView.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui
copying build/lib/drawBot/ui/lineNumberRulerView.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui
copying build/lib/drawBot/ui/preferencesController.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui
copying build/lib/drawBot/ui/splitView.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui
copying build/lib/drawBot/updater.py -> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/__init__.py to __init__.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/__init__.py to __init__.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/baseContext.py to baseContext.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/drawBotContext.py to drawBotContext.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/dummyContext.py to dummyContext.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/gifContext.py to gifContext.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/imageContext.py to imageContext.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/movContext.py to movContext.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/pdfContext.py to pdfContext.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/printContext.py to printContext.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/svgContext.py to svgContext.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/tools/__init__.py to __init__.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/tools/gifTools.py to gifTools.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/tools/imageObject.py to imageObject.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/context/tools/openType.py to openType.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/drawBotDrawingTools.py to drawBotDrawingTools.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/misc.py to misc.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/scriptTools.py to scriptTools.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui/__init__.py to __init__.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui/codeEditor.py to codeEditor.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui/debug.py to debug.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui/drawBotController.py to drawBotController.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui/drawView.py to drawView.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui/lineNumberRulerView.py to lineNumberRulerView.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui/preferencesController.py to preferencesController.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/ui/splitView.py to splitView.pyc
byte-compiling /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot/updater.py to updater.pyc
running install_egg_info
Writing /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drawBot-3.85-py2.7.egg-info

```

The OS version is 10.11.6 (El Capitan) and I I've already used it before (probably not on this os) as a module but this time it gave me this error after I tried to import drawBot:

```
2016-10-09 18:38:29.853 Python[5122:454328] Error loading /Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView:  dlopen(/Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView, 265): no suitable image found.  Did find:
	/Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView: file too short
Traceback (most recent call last):
  File "/Users/user/Desktop/temp.py", line 1, in <module>
    import drawBot
  File "/usr/local/lib/python2.7/site-packages/drawBot/__init__.py", line 1, in <module>
    from drawBotDrawingTools import _drawBotDrawingTool
  File "/usr/local/lib/python2.7/site-packages/drawBot/drawBotDrawingTools.py", line 9, in <module>
    from context import getContextForFileExt
  File "/usr/local/lib/python2.7/site-packages/drawBot/context/__init__.py", line 4, in <module>
    from svgContext import SVGContext
  File "/usr/local/lib/python2.7/site-packages/drawBot/context/svgContext.py", line 8, in <module>
    from xmlWriter import XMLWriter
ImportError: No module named xmlWriter
[Finished in 1.9s with exit code 1]
```

I'm not sure how to fix it. Is it clear to you what is going on?

Thank you

**Comment by typoman** [comment]
Thanks for the quick fix Just, It works now! 

PS: I use drawBot on heavy operations and the application it's not possible to cancel the current session while it's being run so I have to force quit the app. But in the module I can cancel the build in for example in sublime text which is an advantage. I think it could be very useful for the app too.

**Comment by justvanrossum** [comment]
Oh, I thought you just didn't have fonttools installed at all (in the current version it would have worked).

The cancel behaviour is indeed dearly missed, but is really hard to implement if the drawing code is not running in a separate process.

**Comment by typoman** [comment]
I have fonttools but apparently "xmlWriter" only gets imported as a sub module of the fonttools.

**Comment by justvanrossum** [comment]
It's complicated... xmlWriter is part of fontTools, and used to get installed next to the fontTools packages. Then it moved into the package. Then people complained because that broke their code. Then it got moved back. Then the "global" version got deprecated. It will disappear again in the near future. You appear to have this in-between "code-breaking" version of fontTools. I suggest updating.

**Comment by typoman** [comment]
Haha, that's crazy. Thank you for explanation. Could you direct me to the repo which I should update to?

**Comment by anthrotype** [comment]
please, just `pip install fonttools` and your are set.

**Comment by anthrotype** [comment]
or `pip install --upgrade fonttools`, if you have it installed already.

**Comment by justvanrossum** [comment]
Will `pip install fonttools` not upgrade if you have already installed it?

**Comment by anthrotype** [comment]
It will say `Requirement already satisfied (use --upgrade to upgrade)`

**Comment by justvanrossum** [comment]
Perfect.

**Comment by anthrotype** [comment]
`pip install fonttools==3.1.2` will ensure that specific version is installed, up/downgrading if necessary. Or for example, `pip install fonttools>=3.1` or similar will make sure any version greater or equal than 3.1 is installed, etc.
