### ISSUE TITLE
AttributeError in listOpenTypeFeatures()

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#70]
```
font("Hoefler Text")
fontSize(100)
text("Abcde", (50, 100))
print listOpenTypeFeatures()
```

```
Traceback (most recent call last):
  File "<untitled>", line 4, in <module>
  File "git/drawbot/drawBot/drawBotDrawingTools.py", line 1007, in listOpenTypeFeatures
    fontName = self._dummyContext._state.text.fontName
AttributeError: 'FormattedString' object has no attribute 'fontName'
```

**Comment by justvanrossum** [comment]
This has been fixed for a while; not sure in which commit.
