### ISSUE TITLE
OpenFont broke

### ISSUE THREAD

**Issue by thomgb** [typemytype/drawbot#71]
Opening ufo with OpenFont from robofab doesn't work anymore.

``` python
from robofab.world import OpenFont

ufo ="/Users/thom/path.ufo"
f = OpenFont(ufo)

g= f["a"]
```

``` python
Traceback (most recent call last):
  File "<untitled>", line 6, in <module>
  File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/robofab/objects/objectsBase.py", line 184, in __getitem__
AttributeError: 'RFont' object has no attribute 'layers'
```

**Comment by typemytype** [comment]
Ive already added UFO3 libraries
next update I will revert back to UFO2 versions of font related libraries

**Comment by typemytype** [comment]
use `fontParts`

``` python
from fontParts.nonelab import RFont

RFont(path)
```
